// Turns a test case into a standalone Python Playwright project (test.py, requirements.txt,
// .env.example), using the same step parser as the runner so the code matches what a run does.
// Secrets are never written into the code: every {{variable}} is read from the environment / .env.
const fs = require('fs');
const { parseCase } = require('./testcase');
const { parseStep } = require('./actions');

const VAR = /\{\{\s*([\w.-]+)\s*\}\}/g;
const PW_VERSION = '1.55.0';

// {{base_url}} -> LTH_BASE_URL (prefixed: Windows already defines USERNAME, PATH, ...)
const envName = k => 'LTH_' + k.replace(/\W/g, '_').toUpperCase();
// Python string literal (JSON escapes are valid Python escapes).
const pyStr = s => JSON.stringify(String(s));

// Python expression for a step value: "text", var("x"), or var("x") + "text".
function expr(value, used) {
  const s = String(value);
  const parts = [];
  let last = 0;
  for (const m of s.matchAll(VAR)) {
    if (m.index > last) parts.push(pyStr(s.slice(last, m.index)));
    parts.push(`var(${pyStr(m[1])})`);
    used.add(m[1]);
    last = m.index + m[0].length;
  }
  if (last < s.length || !parts.length) parts.push(pyStr(s.slice(last)));
  return parts.join(' + ');
}

function stepCode(a, text, used) {
  switch (a.kind) {
    case 'navigate': return [`page.goto(${expr(a.url, used)})`, 'settle(page)'];
    case 'type': return [`${a.css ? `page.locator(${pyStr(a.css)}).first` : `field(page, ${pyStr(a.target)})`}.fill(${expr(a.value, used)})`];
    case 'select': return [`select2(page, ${pyStr(a.target)}, ${expr(a.value, used)})`];
    case 'selectFirst': return [`select_first(page, ${pyStr(a.css)})`];
    case 'assertVisible': return [`expect(page.locator(${pyStr(a.css)}).first).to_be_visible()`];
    case 'click': return [`${a.css ? `page.locator(${pyStr(a.css)}).first` : `clickable(page, ${pyStr(a.target)})`}.click()`, 'settle(page)'];
    case 'assertTitle': return [`expect_title(page, ${pyStr(a.mode)}, ${expr(a.value, used)})`];
    case 'assertUrl': return [`assert ${expr(a.value, used)} in page.url, "URL should contain " + ${expr(a.value, used)}`];
    case 'assertText': return [`page.get_by_text(${expr(a.value, used)}).first.wait_for(state="visible")`];
    case 'wait': return [`page.wait_for_timeout(${a.ms})`];
    default: return [`# AI step - performed by the AI agent inside LogiTestHub, no fixed code:`, `# ${text.replace(/\n/g, ' ')}`];
  }
}

function readVarsFile(file) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (_) { return {}; }
}

function generate(content, meta = {}) {
  let tc;
  try {
    tc = parseCase(content, meta.base);
  } catch (e) {   // missing helper: show the @import line as-is instead of failing the whole page
    tc = parseCase(content.replace(/^\s*@import\s.*$/gm, ''), meta.base);
    tc.steps.unshift({ section: '', text: `# ${e.message}` });
  }
  const used = new Set();
  const steps = tc.steps.map(s => ({ ...s, kind: parseStep(s.text).kind }));

  const body = [];
  let section = null;
  steps.forEach((s, i) => {
    if (s.section && s.section !== section) {
      if (body.length) body.push('');
      body.push(`# ---- ${s.section} ----`);
      section = s.section;
    }
    body.push(`# ${i + 1}. ${s.text}`);
    body.push(...stepCode(parseStep(s.text), s.text, used));
  });
  const aiCount = steps.filter(s => s.kind === 'unknown').length;
  const varNames = [...used];

  const testPy = `"""${meta.id ? meta.id + ' · ' : ''}${tc.title.replace(/"""/g, "'''")}

Generated by LogiTestHub from the test case steps. Edit the test case, not this file.
Run:
    pip install -r requirements.txt
    python -m playwright install chromium
    copy .env.example to .env and fill the values, then:  python test.py
${aiCount ? `\n${aiCount} step(s) are free-text AI steps: they appear as comments and only run inside LogiTestHub.\n` : ''}"""
import os
import re
import sys
import time

from playwright.sync_api import Page, expect, sync_playwright

try:  # optional: load values from a .env file next to this script
    from dotenv import load_dotenv
    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
except ImportError:
    pass


def var(name: str) -> str:
    """{{name}} in the test case -> LTH_NAME in the environment / .env file."""
    key = "LTH_" + re.sub(r"\\W", "_", name).upper()
    value = os.getenv(key)
    if value is None:
        raise SystemExit(f"Missing {key} - set it in .env (see .env.example)")
    return value


def settle(page: Page) -> None:
    try:
        page.wait_for_load_state("networkidle", timeout=15000)
    except Exception:
        pass


def field(page: Page, name: str):
    """Input found by placeholder, then label, then id/name."""
    key = re.sub(r"\\W", "", name).lower()
    return (page.get_by_placeholder(name)
            .or_(page.get_by_label(name))
            .or_(page.locator(f'input[id="{key}" i], input[name="{key}" i]'))
            .first)


def clickable(page: Page, name: str):
    """Button or link found by its text."""
    return (page.get_by_role("button", name=name)
            .or_(page.get_by_role("link", name=name))
            .or_(page.locator(f'input[type=submit][value*="{name}" i]'))
            .first)


def select2(page: Page, label: str, value: str) -> None:
    """eTail dropdowns are Select2: the real <select> is hidden, so open the widget and pick."""
    select = page.locator("label", has_text=label).first.locator("xpath=following::select[1]")
    widget = select.locator('xpath=following-sibling::span[contains(@class,"select2")][1]')
    if widget.count():
        widget.click()
        search = page.locator(".select2-container--open .select2-search__field")
        if search.count():
            search.fill(value)
        page.locator(".select2-results__option", has_text=value).first.click()
    else:
        select.select_option(label=value)


def select_first(page: Page, css: str) -> None:
    """Picks the first real option of the <select> (skips the empty "-- Select --") and fires change,
    which also updates a Select2 widget - same as the LogiTestHub runner."""
    picked = page.locator(css).first.evaluate("""el => {
        const o = [...(el.options || [])].find(x => x.value && !x.disabled);
        if (!o) return null;
        el.value = o.value;
        if (window.jQuery) window.jQuery(el).trigger('change'); else el.dispatchEvent(new Event('change', { bubbles: true }));
        return o.value;
    }""")
    assert picked is not None, f"{css} has no options to pick"
    settle(page)


def expect_title(page: Page, mode: str, want: str) -> None:
    """Same rule as the LogiTestHub runner: case-insensitive, waits up to 10 s."""
    end = time.time() + 10
    while True:
        try:
            title = page.title().lower()
        except Exception:  # page is navigating (eTail logs in over AJAX, then redirects)
            title = ""
        if (title == want.lower()) if mode == "is" else (want.lower() in title):
            return
        if time.time() > end:
            raise AssertionError(f'Title should {"be" if mode == "is" else "contain"} "{want}", got "{page.title()}"')
        page.wait_for_timeout(300)


def test_case(page: Page) -> None:
${body.map(l => (l ? '    ' + l : '')).join('\n')}


if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=os.getenv("HEADLESS", "true").lower() != "false")
        page = browser.new_page(viewport={"width": 1366, "height": 768})
        try:
            test_case(page)
            print("PASSED")
        except Exception as err:
            print(f"FAILED: {err}")
            sys.exit(1)
        finally:
            browser.close()
`;

  const requirements = `playwright==${PW_VERSION}\npython-dotenv>=1.0\n`;

  const raw = readVarsFile(meta.varsFile);
  const env = [
    '# Copy to .env and fill in. Never commit the real .env file.',
    ...varNames.map(k => {
      const e = raw[k];
      const secret = e && typeof e === 'object' && e.secret;
      const val = e && typeof e === 'object' ? e.value : e;
      const safe = !secret && val != null && !/\{\{/.test(String(val)) ? String(val) : '';
      return (secret ? '# secret - fill in, never share\n' : '') + `${envName(k)}=${safe}`;
    }),
    '# Set HEADLESS=false to watch the browser',
    'HEADLESS=true',
  ].join('\n') + '\n';

  return {
    title: tc.title,
    steps,
    vars: varNames,
    files: { 'test.py': testPy, 'requirements.txt': requirements, '.env.example': env },
  };
}

module.exports = { generate, envName };
